### ISSUE TITLE
@carbon/ibm-products breaks <Tag type="outline">

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#5661]
### Package

Carbon for IBM Products

### Description

The CSS from @carbon/ibm-products breaks the display of Tags with outlines, adding an extra outline around the text:

<img width="41" alt="Screenshot 2024-07-11 at 10 40 35" src="https://github.com/carbon-design-system/ibm-products/assets/69599/75b9195b-13c2-49b6-9126-225b5f7f5d8c">

(I know that `<Tag>` comes from @carbon/react, not @carbon/ibm-products, but the error is caused by @carbon/ibm-products.)

### Cause of the bug

Look at the last `Tag` in https://react.carbondesignsystem.com/?path=/story/components-tag--read-only, which displays correctly because @carbon/ibm-products isn't loaded on that page.

@carbon/react renders the `Tag` with strange markup where the `cds--tag--outline` is used on two nodes:

```html
<div class="cds--tag some-class cds--tag--outline" id="tag-51">
   <span title="Tag content" class="cds--tag__label cds--tag--outline" dir="ltr">Tag content</span>
</div>
```

Then @carbon/styles has weird CSS to counteract that by ignoring the `cds--tag--outline` outline on the `<span>`:

```scss
.#{$prefix}--tag--outline:not(.#{$prefix}--tag--operational):not(span):not(
    [disabled]
  ) {
  ...
}
```

So far, everything is working, albeit with a questionable implementation.   But then @carbon/ibm-products' index-without-carbon.css includes this CSS:

```scss
.cds--tag--outline:not(.cds--tag--operational) {
    background-color: var(--cds-background, #ffffff);
    color: var(--cds-text-primary, #161616);
    outline: 1px solid var(--cds-background-inverse, #393939);
    outline-offset: -1px
}
```

I don't understand where that CSS came from but it's doubly problematic:

* You are including CSS for Carbon whereas that file is only supposed to have CSS for ibm-products.
* You're including weird CSS that breaks the display of `<Tag type="outline">`.

### Component(s) impacted

@carbon/react

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0-rc1

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/goofy-jasper-7m49r3?file=%2Fnode_modules%2F%40carbon%2Freact%2Flib%2Fcomponents%2FTag%2FTag.js%3A133%2C47

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by devadula-nandan** [comment]
update:
yup, can confirm, that this got fixed in the latest @carbon/react


https://github.com/user-attachments/assets/ae38c7a5-bda2-4d80-b260-0f7a31f0a25e

**Comment by wkeese** [comment]
@devadula-nandan - I'm glad the visual glitch is gone but as I wrote above, don't you think it's wrong for @carbon/ibm-products to have CSS altering Carbon itself.  The example I posted was this:

```scss
.cds--tag--outline:not(.cds--tag--operational) {
    background-color: var(--cds-background, #ffffff);
    color: var(--cds-text-primary, #161616);
    outline: 1px solid var(--cds-background-inverse, #393939);
    outline-offset: -1px
}
```

But there's a lot more.
