### ISSUE TITLE
Datagrid: useFloatingScroll() broken

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#5941]
### Package

Carbon for IBM Products

### Description

Datagrid has two ways of supporting horizontal and vertical scrolling:

1. Infinite scrolling as demonstrated on https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--with-virtualized-data&globals=viewport:basic, using the `withVirtualScroll` flag.
2. The simpler `useFloatingScroll()`, which makes sense for when the grid has paging, but the Datagrid's size is too small to show all the rows and/or columns in a single page.

I don't want to use option 1, as it's overkill for a table with paging, and also IIRC has other issues, like hardcoding the table height to a value that needs to be specified in Javascript.

However, `useFloatingScroll()` is broken in multiple ways:

1. Setting height on the table doesn't work.  It's ignored.
2. The `useFloatingScroll()` plugin isn't exported from @carbon/ibm-products top level.
3. The header column does not scroll along with the table body.

In the end, I worked around the issues by basically implementing everything myself, hacking the SCSS to work:

```scss
:global(.#{prefixes.$ibm}--datagrid__grid-container),
:global(.#{prefixes.$ibm}--datagrid__table-container),
table,
tbody {
  // Show horizontal scrollbar at bottom of tab even if there are only a few rows.
  height: 100%;

  // Need to set min-height to 0 or else height explodes (and we get no scrollbar).
  min-height: 0;
}

// Put scrollbar on data rows, rather than the entire table, so that the table headers stay in view.
thead {
  display: block;
  overflow: hidden;

  &::after {
    // Note: If the <tbody> has a vertical scrollbar we should add a little right-padding or margin to
    // compensate, to make the length of the thead --> tr match the tbody --> tr.  But it depends on
    // 1. If there's a scrollbar.
    // 2. scrollbar-width property (set to "thin" by carbon).
    // 3. Mac or PC.
    // 4. Chrome or Firefox.
  }
}

tbody {
  display: block;
  overflow: auto;
}
```

And then implementing my own scroll alignment:

```tsx
// Scroll the headers (thead) as the table body (tbody) is scrolled.  Should be handled by useFloatingScroll(),
// but useFloatingScroll() looks for a thead > div, and there's no such <div>.  See
// https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom
// for why useCallback() is recommended over useRef() + useEffect().
const gridRef = useCallback((root: HTMLElement | null) => {
root?.addEventListener(
  "scroll",
  (event: Event) => {
    const virtualBody = event.target as HTMLDivElement;
    if (virtualBody) {
      const header = root.querySelector("thead");
      if (header) {
        header.scrollLeft = virtualBody.scrollLeft;
      }
    }
  },
  true
);
}, []);

return (
  <Datagrid
    ref={gridRef}
    datagridState={{
      className: styles.grid, // Datagrid takes class name from datagridState, ignoring any top level className prop.
      ...datagridState,
    }}
  />
```

Note that the main problem with the existing scroll code is that it looks for a `thead > div`, but there's no `<div>` inside the `<thead>`.

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-qcefwb-kgcczw?file=src%2FExample%2FExample.jsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
