### ISSUE TITLE
@carbon/ibm-products' CSS repeats @carbon/style's CSS

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#5942]
### The problem

ibm-products' index-without-carbon.css repeats a lot of the CSS from @carbon/styles, thus bloating all the IBM products.

For example, it includes this CSS

```css
.cds--tag--outline:not(.cds--tag--operational):not(span):not([disabled]) {
  background-color: var(--cds-background, #ffffff);
  color: var(--cds-text-primary, #161616);
  outline: 1px solid var(--cds-background-inverse, #393939);
  outline-offset: -1px;
}
.cds--tag--outline:not(.cds--tag--operational):not(span):not([disabled]).cds--tag--operational {
  border: 1px solid var(--cds-background, #ffffff);
}
.cds--tag--outline:not(.cds--tag--operational):not(span):not([disabled]).cds--tag--operational:hover {
  background-color: var(--cds-layer-hover);
}
.cds--tag--outline:not(.cds--tag--operational):not(span):not([disabled]) .cds--tag__close-icon:hover {
  background-color: var(--cds-layer-hover);
}
```

The problem is presumably that you have the wrong @use statements.  Often code will do something like:

```scss
@use '@carbon/react/scss/components/tag';
```

but that is **wrong** because it pulls in a bunch of CSS rules, whereas what you really wanted was just definitions for tokens (and maybe mixins).   So this is better: 

```scss
@use '@carbon/react/scss/components/tag/tokens';
```

**_Note that this is just an example.  The problem is not limited to tags._**

### The solution

Update @use statements.

### Owner/main maintainer(s)

not sure

### Product/offering

IKC

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
