### ISSUE TITLE
[BUG]: On `Datagrid`, redundant vertical scroll when an expandable row is set with size `xs`

### ISSUE THREAD

**Issue by atar9500** [carbon-design-system/ibm-products#6589]
### Package

Carbon for IBM Products

### Description

When rendering a `Datagrid` with expandable rows and setting the row size to extra small (`xs`) - we are having an additional empty space on the bottom (marked with red), which the vertical scrollbar to be shown.

![Image](https://github.com/user-attachments/assets/6a0a3d10-4033-43be-8a8c-85b75b24ef62)

It is caused due to the expanding button taking more space (`min-height: 40px;`) than the table cell it is rendered on.

For now, as a workaround we do:

```scss
:global {
  .c4p--datagrid__expandable-row-cell {
    padding-top: 0 !important;
    padding-bottom: 0 !important;
    align-items: center !important;
    justify-content: center !important;
  }
  .c4p--datagrid__row-expander {
    height: 100% !important;
    min-height: unset !important;
    max-height: 40px !important;
  }
}
```

### Component(s) impacted

It is impacting `Datadrid` as we can see here:

![Image](https://github.com/user-attachments/assets/378473fa-8543-4fb9-8fc8-e950050fb34d)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.50.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

-

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/deprecated-datagrid-datagrid-expandablerow--expandable-row-story&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

1. Click on the setting button (top-right).
2. Set Row Size to extra small (`xs`).
3. Set Items Per Page to 10 or 5.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
