### ISSUE TITLE
Investigate removal of `framer-motion`

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6678]
While `framer-motion` has been a very convenient tool in orchestrating animations and transitions, we've faced issues in managing it as a dependency given our requirement for continued support of React 16 and up.

After doing a quick review of where and how we're using it, I think we should be able to do everything we're currently doing with `framer-motion` now with native css. For example, creating an animation on render (which we've commonly relied on `AnimatePresence` for), can be done all in css now, here is an quick example:

```css
.element {
  transform: translateY(2rem);
  transition-property: opacity, transform;
  transition-duration: 350ms;
  transition-behavior: allow-discrete;
}
.element.hide {
  opacity: 0;
}
.element.show {
  @starting-style {
    opacity: 0;
  }
  opacity: 1;
  transform: translateY(0);
}
```

See codepen example [here](https://codepen.io/mattgallo/pen/OPLQamx?editors=1111).

With the `allow-discrete` transition-property value, values like `display` can also be used in transitions.
