### ISSUE TITLE
Discovery: do some exploration around how we would support testing across multiple React versions

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6988]

**Comment by davidmenendez** [comment]
i think we could do this easily by just utilizing the [matrix strategy](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-expanding-configurations) functionality in gh actions. here's an example implementation from [zustand](https://github.com/pmndrs/zustand/blob/main/.github/workflows/test-multiple-versions.yml).

i think something as simple as this should be enough to ensure that the library works with multiple versions of react
```
jobs:
  test_major_versions:
    strategy:
      matrix:
        react: [17, 18]
    runs-on: ubuntu-latest
    steps:
      - run: yarn
      - run: yarn add react@${{ matrix.react }} react-dom@${{ matrix.react }}
      - run: yarn test:c4p
```
