### ISSUE TITLE
@carbon/ibm-products' CSS still repeats @carbon/style's CSS

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#7041]
### Package

Carbon for IBM Products

### Description

@carbon/ibm-products' index-without-carbon.css still contains a bunch of CSS from Carbon.  It was supposedly fixed with #5942 but it wasn't, or at least not completely.  For example:

```css
.cds--css-grid {
  --cds-grid-gutter-start: calc(var(--cds-grid-gutter) / 2);
  --cds-grid-gutter-end: calc(var(--cds-grid-gutter) / 2);
  --cds-grid-column-hang: calc(var(--cds-grid-gutter) / 2);
  display: grid;
  grid-template-columns: repeat(var(--cds-grid-columns), minmax(0, 1fr));
  inline-size: 100%;
  margin-inline: auto;
  max-inline-size: 99rem;
  padding-inline: var(--cds-grid-margin);
}
```

and

```css
.cds--sm\:col-span-2 {
  --cds-grid-columns: 2;
  display: block;
  grid-column: span 2/span 2;
} 
```

and

```css
.cds--layout-constraint--density__min-condensed {
  --cds-layout-density-padding-inline-min: var(--cds-layout-density-padding-inline-condensed, 0.5rem);
} 
```

### Component(s) impacted

It makes all the components slower by bloating the build.

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.61.0

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

npm install @carbon/ibm-products@2.61.0
cd node_modules/@carbon/ibm-products/css
fgrep -n .cds index-without-carbon.css |grep -v c4p

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues
